### PR TITLE
Reimplement aero visualization

### PR DESCRIPTION
**Pull request by mjn33**
This patch reimplements the old aero visualization options introduced in FAR 0.14.2.

There are a few things I should mention though:
 * For non-wing pieces Cl / Cd is calculated using exposed area (maybe use oldFAR method instead?). Wing pieces use wing area as previously.
 * A different method is used for tinting, it uses the same method as KSP's thermal overlay debug option. The advantage of this is the tinting should be visible from all viewing angles, previously certain viewing angles would make the tinting hard to see.
 * I haven't included the rebuilt assembly, to prevent merge issues

Any changes/bugfixes you want made to this just let me know, and I'll push them to this PR.

### CODE REVIEW

**Comment by ferram4** [comment]
The right way to show Cl and Cd would really be for *all* parts to make use of the reference value in the FlightData window.  It would make everything fully and completely consistent.

**Comment by mjn33** [comment]
Shouldn't wing pieces be treated on a per-part basis though? For example, if the reference value in the flight data window is used for wing pieces, a wing made from a single piece would be tinted more than an identical wing made from two pieces.

**Comment by ferram4** [comment]
...true.

Ah, I guess then that leaving things using exposedArea should be fine.  Mostly just thinking about ways to try and get comparable lift coefficients between wings and fuselages, but that's a little difficult to manage.  Using exposedArea should be fine for now, I think.

**Comment by mjn33** [comment]
Yeah, now thinking on it a bit more, this problem would exist for non-wing parts as well. E.g. a fuselage made from many short Mk3 fuselage parts vs a fuselage made from fewer long Mk3 fuselage parts. 

Cheers for merging in any case though!

**Pull request merged**
